'use strict';
const projects=[
{id:'wynn-al-marjan',name:'Wynn Al Marjan Island',location:'Ras Al Khaimah',group:'landmark',scope:'Specialist GRG, ceiling and wall partition works across hospitality venues.',client:'Island AMI 3',contractor:'ALEC Fit Out',status:'Ongoing in the supplied profile'},
{id:'burj-binghatti',name:'Burj Binghatti Jacob & Co Residences',location:'Business Bay, Dubai',group:'landmark',scope:'200,000 sqm of gypsum ceilings and partitions.',client:'Binghatti Properties Investments Limited',contractor:'Granada Europe Engineering Construction LLC',status:'Ongoing in the supplied profile; target October 2026'},
{id:'district-01-west',name:'District 01 West',location:'Dubai',group:'landmark',scope:'150,000 sqm of ceiling and partition works.',client:'Meydan Group LLC',contractor:'GINCO General Contracting LLC',status:'Ongoing in the supplied profile; target June 2026 does not establish completion'},
{id:'dubai-harbour',name:'Dubai Harbour Residences',location:'Dubai Harbour',group:'landmark',scope:'Ceiling and partition works within the residential development.',client:'SHAMAL Holding',contractor:'Khansaheb Civil Engineering LLC',status:'Started June 2026, according to the supplied profile'},
{id:'serenia-living',name:'Serenia Living',location:'Palm Jumeirah, Dubai',group:'landmark',scope:'Two towers; 120,000 sqm of gypsum ceiling per tower, as reported.',client:'Serenia Residences Limited',contractor:'Khansaheb Civil Engineering',status:'Project page reports snagging; register reports completed'},
{id:'dubai-exhibition',name:'Dubai Exhibition Centre',location:'Expo City, Dubai',group:'landmark',scope:'30,000 sqm of gypsum partitions.',client:'Dubai World Trade Center',contractor:'Khansaheb Civil Engineering',status:'Completed January 2026, according to the supplied profile'},
{id:'forte-towers',name:'Forte Towers, D1 / D2',location:'Downtown Dubai',group:'residential',scope:'False gypsum ceilings and fit-out works, including wall coverings, flooring and carpet packages.',client:'Emaar',contractor:'Target',status:'Completed in the supplied profile'},
{id:'golf-ville',name:'Golf Ville',location:'Dubai Hills, Dubai',group:'residential',scope:'Gypsum and cement board ceilings.',client:'Emaar',contractor:'GINCO',status:'Completed in the supplied profile'},
{id:'golf-place',name:'Golf Place',location:'Dubai Hills, Dubai',group:'residential',scope:'Gypsum and cement board ceilings.',client:'Emaar',contractor:'Trojan',status:'Completed in the supplied profile'},
{id:'murooj-al-furjan',name:'Murooj Al Furjan',location:'Al Furjan, Dubai',group:'residential',scope:'Gypsum and cement board ceilings.',client:'Nakheel',contractor:'GINCO',status:'Completed in the supplied profile'},
{id:'green-view',name:'The Green View',location:'South Dubai',group:'residential',scope:'Gypsum ceilings and cement board works.',client:'Emaar',contractor:'GINCO',status:'Completed in the supplied profile'},
{id:'binghatti-orchid',name:'Binghatti Orchid',location:'JVC, Dubai',group:'residential',scope:'Gypsum ceilings and wall partitions.',client:'Binghatti Properties Investments Limited',contractor:'Granada Europe',status:'Completed in the supplied profile'},
{id:'binghatti-dusk',name:'Binghatti Dusk',location:'JVC, Dubai',group:'residential',scope:'Gypsum ceilings and wall partitions.',client:'Binghatti Properties Investments Limited',contractor:'Granada Europe',status:'Completed in the supplied profile'},
{id:'j-one-tower',name:'J One Tower',location:'Downtown Dubai',group:'residential',scope:'Gypsum ceilings and wall partitions.',client:'Dar Al Arkan',contractor:'Shapoorji Pallonji',status:'Completed in the supplied profile'},
{id:'empower-headquarters',name:'EMPOWER Headquarters',location:'Jadaf, Dubai',group:'workplace',scope:'Gypsum ceilings and glass mat board partitions.',client:'EMPOWER',contractor:'China Railway',status:'Completed in the supplied profile'},
{id:'boulevard-heights',name:'Boulevard Heights',location:'Downtown Dubai',group:'workplace',scope:'Wallpaper, carpet and wood cladding.',client:'Emaar',contractor:'Target',status:'2018, as stated in the supplied profile'},
{id:'sheikh-zayed-showroom',name:'Sheikh Zayed Showroom',location:'Dubai, UAE',group:'workplace',scope:'Wood flooring and wood cladding at Sheikh Zayed Showroom, Plot 21.',client:'Omniyat',contractor:'Arcane Interior Decorations',status:'2021, as stated in the supplied profile'}
];
const icons={landmark:'<path d="M4 21V7l8-4 8 4v14M9 21v-4h6v4M8 9h1m6 0h1M8 12h1m6 0h1M2 21h20"/>',residential:'<path d="m3 11 9-8 9 8M5 10v11h14V10M9 21v-7h6v7M8 10h1m6 0h1"/>',workplace:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12h18M10 12v3h4v-3"/>'};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const asset=p=>'project-'+p.id+'.png';const navigation=$('#navigation');const menuButtons=$$('[data-menu]');const dialog=$('#project-dialog');
let menuCloseTimer;let pinnedMenu=null;
const hoverNavigation=window.matchMedia('(hover: hover) and (pointer: fine)');
function closeMenus(){clearTimeout(menuCloseTimer);pinnedMenu=null;for(const b of menuButtons){b.setAttribute('aria-expanded','false');$('#'+b.dataset.menu).hidden=true;}}
function closeNavigation(){navigation.classList.remove('open');$('.mobile-toggle').setAttribute('aria-expanded','false');}
function loadHero(img,p){img.dataset.loaded='false';img.setAttribute('aria-busy','true');img.onload=()=>{img.dataset.loaded='true';img.setAttribute('aria-busy','false');};img.onerror=()=>{img.dataset.loaded='error';img.setAttribute('aria-busy','false');};img.alt='Illustrative interior concept for '+p.name;img.src=asset(p);}
function menuHero(p){loadHero($('#menu-image'),p);$('#menu-caption').textContent=p.name;$('.menu-hero').hidden=false;}
for(const p of projects){const button=document.createElement('button');button.className='menu-project';button.dataset.project=p.id;button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[p.group]+'</svg>';const name=document.createElement('span');name.textContent=p.name;const location=document.createElement('small');location.textContent=p.location;name.append(location);button.append(name);button.addEventListener('pointerenter',()=>menuHero(p));button.addEventListener('focus',()=>menuHero(p));button.addEventListener('click',()=>openProject(p));$('#menu-'+p.group).append(button);
const tile=document.createElement('button');tile.className='project-tile';tile.dataset.group=p.group;tile.dataset.project=p.id;const small=document.createElement('small');small.textContent=p.group==='landmark'?'Landmark project':p.group==='residential'?'Residential portfolio':'Workplace & fit-out';const heading=document.createElement('h3');heading.textContent=p.name;const loc=document.createElement('p');loc.textContent=p.location;const arrow=document.createElement('span');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');tile.append(small,heading,loc,arrow);tile.addEventListener('click',()=>openProject(p));$('#project-grid').append(tile);}
function openMenu(b){clearTimeout(menuCloseTimer);if(b.getAttribute('aria-expanded')==='true')return;closeMenus();b.setAttribute('aria-expanded','true');$('#'+b.dataset.menu).hidden=false;if(b.dataset.menu==='projects-menu')menuHero(projects[0]);}
function scheduleMenuClose(){clearTimeout(menuCloseTimer);menuCloseTimer=setTimeout(()=>{if(!pinnedMenu)closeMenus();},220);}
for(const b of menuButtons){
 const panel=$('#'+b.dataset.menu);
 b.addEventListener('pointerenter',()=>{if(hoverNavigation.matches)openMenu(b);});
 b.addEventListener('pointerleave',()=>{if(hoverNavigation.matches)scheduleMenuClose();});
 panel.addEventListener('pointerenter',()=>clearTimeout(menuCloseTimer));
 panel.addEventListener('pointerleave',()=>{if(hoverNavigation.matches)scheduleMenuClose();});
 b.addEventListener('click',()=>{if(pinnedMenu===b){closeMenus();return;}openMenu(b);pinnedMenu=b;});
 b.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();openMenu(b);pinnedMenu=b;panel.querySelector('a,button')?.focus();}});
}
 document.addEventListener('focusin',e=>{if(!e.target.closest('.mega')&&!e.target.closest('[data-menu]'))closeMenus();});
document.addEventListener('click',e=>{if(!e.target.closest('.mega')&&!e.target.closest('[data-menu]'))closeMenus();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenus();closeNavigation();}});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{closeMenus();closeNavigation();}));
$('.mobile-toggle').addEventListener('click',()=>{const open=!navigation.classList.contains('open');navigation.classList.toggle('open',open);$('.mobile-toggle').setAttribute('aria-expanded',String(open));if(!open)closeMenus();});
$$('[data-filter]').forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$$('.project-tile').forEach(t=>t.hidden=button.dataset.filter!=='all'&&t.dataset.group!==button.dataset.filter);}));
let projectTrigger;
function openProject(p){projectTrigger=document.activeElement;closeMenus();closeNavigation();loadHero($('#dialog-image'),p);$('#dialog-title').textContent=p.name;$('#dialog-location').textContent=p.location;$('#dialog-scope').textContent=p.scope;const details=$('#dialog-details');details.replaceChildren();for(const [label,value]of [['CLIENT / DEVELOPER',p.client],['CONTRACTOR',p.contractor],['SOURCE PROGRAMME',p.status]]){const wrap=document.createElement('div');const dt=document.createElement('dt');dt.textContent=label;const dd=document.createElement('dd');dd.textContent=value;wrap.append(dt,dd);details.append(wrap);}document.body.classList.add('modal-open');dialog.showModal();}
$('.dialog-close').addEventListener('click',()=>dialog.close());$('#dialog-contact').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');projectTrigger?.focus();});
const theme=$('#theme');function applyTheme(dark){document.body.classList.toggle('dark',dark);theme.textContent=dark?'☀':'☾';theme.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');}try{applyTheme(localStorage.getItem('arcane-theme')==='dark');}catch{}theme.addEventListener('click',()=>{const dark=!document.body.classList.contains('dark');applyTheme(dark);try{localStorage.setItem('arcane-theme',dark?'dark':'light');}catch{}});
const music=$('#background-music');const musicButton=$('#music');music.volume=.2;function syncMusic(){const playing=!music.paused;musicButton.setAttribute('aria-pressed',String(playing));musicButton.setAttribute('aria-label',playing?'Pause background music':'Enable background music');$('#music-label').textContent=playing?'Pause music':'Enable music';$('#music-status').textContent=playing?'Lounge Vibe is playing on loop.':'Background music is paused.';}musicButton.addEventListener('click',async()=>{if(!music.paused){music.pause();return;}try{await music.play();}catch{$('#music-status').textContent='Unable to play background music. Please try again.';}});music.addEventListener('play',syncMusic);music.addEventListener('pause',syncMusic);music.addEventListener('error',()=>{$('#music-status').textContent='Background music could not be loaded.';});
