'use strict';
const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');
const generatePages=function generatePages(knowledge,copy,template){
const base="https://arcane-rp.online";
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
knowledge.company.content=copy.company;knowledge.approachContent=copy.approach;
knowledge.profile.access="Use the pulsing circular download button beside Discuss your project in the navigation. Enter an email to download; the email stays in the browser and is not stored.";
for(const p of knowledge.projects)p.content=copy.projects[p.id];
for(const s of knowledge.services)s.content=copy.services[s.id];
const projects=knowledge.projects,services=knowledge.services;
const projectUrl=p=>"/projects/"+p.id+"/",serviceUrl=s=>"/expertise/"+s.id+"/";
const groupLabel=g=>g==="landmark"?"Landmark project":g==="residential"?"Residential portfolio":"Workplace & fit-out";
const icons={landmark:'<path d="M4 21V7l8-4 8 4v14M9 21v-4h6v4M8 9h1m6 0h1M8 12h1m6 0h1M2 21h20"/>',residential:'<path d="m3 11 9-8 9 8M5 10v11h14V10M9 21v-7h6v7M8 10h1m6 0h1"/>',workplace:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12h18M10 12v3h4v-3"/>'};
let shell=template;
for(const g of Object.keys(icons))shell=shell.replace(`<div id="menu-${g}"></div>`,`<div id="menu-${g}">${projects.filter(p=>p.group===g).map(p=>`<a class="menu-project" data-project="${p.id}" href="${projectUrl(p)}"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[g]}</svg><span>${esc(p.name)}<small>${esc(p.location)}</small></span></a>`).join("")}</div>`);
shell=shell.replace('<div id="project-grid" class="project-grid"></div>',`<div id="project-grid" class="project-grid">${projects.map(p=>`<a class="project-tile" data-group="${p.group}" data-project="${p.id}" href="${projectUrl(p)}"><small>${groupLabel(p.group)}</small><h3>${esc(p.name)}</h3><p>${esc(p.location)}</p><span aria-hidden="true">↗</span></a>`).join("")}</div>`);
const allMain=shell.match(/<main id="main">([\s\S]*?)<\/main>/)[1];
let companyMain=allMain.slice(0,allMain.indexOf('<section id="approach-page"'));
let approachMain=allMain.slice(allMain.indexOf('<section id="approach-page"'),allMain.indexOf('<section id="project-page"'));
let homeMain=allMain.slice(allMain.indexOf('<section id="home"'));
const paragraphs=ps=>ps.map(p=>"<p>"+esc(p)+"</p>").join("");
const blocks=rows=>rows.map(([heading,ps])=>`<section class="content-block"><h2>${esc(heading)}</h2>${paragraphs(ps)}</section>`).join("");
const faq=(rows,title)=>`<section class="section faq-section" aria-label="${esc(title)}"><div class="reading-heading"><p class="eyebrow">USEFUL INFORMATION</p><h2>${esc(title)}</h2></div><div class="faq-list">${rows.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join("")}</div></section>`;
const cta=()=>`<section class="section page-cta"><div><p class="eyebrow">YOUR NEXT SPECIALIST PACKAGE</p><h2>A clear brief.<br><em>A considered start.</em></h2><p>Share your project location, the space you have in mind and the specialist work required.</p></div><div class="cta-actions"><a class="button" href="/#enquiry">Discuss your project ↗</a><a class="text-link" href="mailto:info@arcane.ae">Email the Arcane team</a><a class="text-link" href="tel:+97145707248">+971 4 570 7248</a></div></section>`;
const related=(title,links)=>`<section class="section related-links"><p class="eyebrow">EXPLORE ARCANE</p><h2>${esc(title)}</h2><div class="related-grid">${links.map(l=>`<a href="${l.url}"><span class="eyebrow">${esc(l.label)}</span><h3>${esc(l.name)}</h3><p>${esc(l.description)}</p><span class="related-arrow" aria-hidden="true">↗</span></a>`).join("")}</div></section>`;
const serviceLinks=ids=>ids.map(id=>services.find(s=>s.id===id)).map(s=>({url:serviceUrl(s),label:"SPECIALIST EXPERTISE",name:s.name,description:s.scope}));
const projectLinks=ids=>ids.map(id=>projects.find(p=>p.id===id)).map(p=>({url:projectUrl(p),label:p.location,name:p.name,description:p.scope}));
companyMain=companyMain.replace(" hidden","").replace('loading="lazy"','fetchpriority="high"');
companyMain=companyMain.trim().replace(/<\/section>$/,"")+`<div class="section reading-section"><div class="reading-heading"><p class="eyebrow">INTERIOR DECORATION IN DUBAI &amp; THE UAE</p><p class="lead">${esc(copy.company.intro)}</p></div><div class="reading-body">${blocks(copy.company.sections)}</div></div>`+related("Three specialist capabilities",serviceLinks(services.map(s=>s.id)))+faq(copy.company.faqs,"About Arcane")+cta()+"</section>";
approachMain=approachMain.replace(" hidden","").replace('loading="lazy"','fetchpriority="high"').replace(/<div class="section editorial-next">[\s\S]*?<\/div>/,"");
approachMain=approachMain.trim().replace(/<\/section>$/,"")+`<div class="section reading-section"><div class="reading-heading"><p class="eyebrow">FROM THE FIRST BRIEF TO THE FINISH</p><p class="lead">${esc(copy.approach.intro)}</p></div><div class="reading-body">${blocks(copy.approach.sections)}</div></div>`+faq(copy.approach.faqs,"Working with our team")+related("Connect the process to the work",serviceLinks(services.map(s=>s.id)))+cta()+"</section>";
homeMain=homeMain.replace('<div class="stats">','<a class="text-link overview-link" href="/company/">More about the company ↗</a><div class="stats">');
homeMain=homeMain.replace('<section id="contact"','<div class="section overview-process-link"><a class="text-link" href="/approach/">Explore our full approach ↗</a></div><section id="contact"');
function detailMain(p,isService){
 const c=p.content,image="/"+(p.image||"project-"+p.id+".png");
 const h1=isService&&p.id==="ceilings"?"Ceilings &amp;<br>partitions":esc(p.name);
 const facts=isService?p.facts:[["Location",p.location],["Client / developer",p.client],["Contractor",p.contractor]];
 const relatedBlock=isService?related("Relevant project references",projectLinks(c.projects)):related("Explore this specialist expertise",serviceLinks(c.services));
 const moreProjects=isService?"":related("More from the portfolio",projectLinks(projects.filter(q=>q.id!==p.id&&q.group===p.group).slice(0,3).map(q=>q.id)));
 return `<section id="project-page" aria-labelledby="project-hero-title"><div class="hero project-hero"><img id="project-hero-image" class="hero-image" src="${image}" alt="Illustrative interior concept for ${esc(p.name)}" width="1672" height="941" fetchpriority="high"><div class="hero-shade"></div><div class="hero-copy"><a class="project-back" href="/#${isService?"expertise":"projects"}">← ${isService?"Our expertise":"All projects"}</a><p id="project-hero-location" class="eyebrow">${esc(isService?p.location:p.location+" · "+groupLabel(p.group))}</p><h1 id="project-hero-title" tabindex="-1">${h1}</h1><p id="project-hero-intro">${esc(p.scope)}</p><div class="hero-buttons"><a class="button" href="#project-details">${isService?"Explore this expertise":"Explore the project"} ↓</a><a class="text-link" href="/#enquiry">Discuss ${isService?"your specialist package":"a similar project"}</a></div></div><span class="hero-credit">Illustrative interior concept</span></div><div id="project-details" class="section project-details"><div><p class="eyebrow">${isService?"OUR SPECIALIST CAPABILITY":"THE IDENTIFIED SPECIALIST PACKAGE"}</p><h2>${esc(c.sections[0][0])}</h2><p id="project-scope" class="lead">${esc(p.scope)}</p></div><dl id="project-facts">${facts.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("")}</dl></div><div class="section reading-section"><div class="reading-heading"><p class="eyebrow">${isService?"CAPABILITY, PROCESS & APPLICATION":"SCOPE, CONTEXT & COORDINATION"}</p><p class="lead">${esc(isService?"Understand the specialist work, how it connects to the complete interior and what to share for a new project enquiry.":"Explore the scope recorded for "+p.name+" and considerations relevant to a similar specialist interior package.")}</p></div><div class="reading-body">${blocks(c.sections)}</div></div>${isService?faq(c.faqs,"About this expertise"):""}${relatedBlock}${moreProjects}${cta()}</section>`;
}
const org={"@type":"HomeAndConstructionBusiness","@id":base+"/#organization",name:"Arcane Interior Decorations",url:base+"/",logo:{"@type":"ImageObject",url:base+"/arcane-logo.jpg"},image:base+"/arcane-logo.jpg",description:"Established in 2004, Arcane Interior Decorations specialises in GRG, ceilings, partitions and interior fit-out across the UAE.",email:knowledge.contact.email,telephone:knowledge.contact.phone,address:{"@type":"PostalAddress",streetAddress:"Emaar Business Park, Building No. 1, Office No. 530, Sheikh Zayed Road",addressLocality:"Dubai",addressCountry:"AE"},areaServed:{"@type":"Country",name:"United Arab Emirates"},contactPoint:[{"@type":"ContactPoint",telephone:knowledge.contact.phone,email:knowledge.contact.email,contactType:"Project enquiries",areaServed:"AE"},{"@type":"ContactPoint",telephone:knowledge.contact.whatsapp,url:knowledge.contact.whatsappUrl,contactType:"WhatsApp project enquiries",areaServed:"AE"}]};
const site={"@type":"WebSite","@id":base+"/#website",url:base+"/",name:"Arcane Interior Decorations",publisher:{"@id":org["@id"]},inLanguage:"en"};
const pages=[{url:"/",type:"WebPage",section:"home",title:"GRG, Ceilings & Interior Fit-Out in UAE | Arcane",description:"Arcane Interior Decorations: specialist GRG, ceilings, partitions and interior fit-out in Dubai and the UAE. Established in 2004. Explore our project portfolio.",name:"Arcane Interior Decorations",main:homeMain,image:"/arcane-home.png"},
{url:"/company/",type:"AboutPage",section:"company",title:copy.company.title,description:copy.company.description,name:"The company",main:companyMain,image:"/arcane-company-hero.jpg"},
{url:"/approach/",type:"WebPage",section:"approach",title:copy.approach.title,description:copy.approach.description,name:"Our approach",main:approachMain,image:"/arcane-approach-hero.jpg"}];
for(const p of projects)pages.push({url:projectUrl(p),type:"WebPage",section:"projects",title:p.name+" | Specialist Interior Works | Arcane",description:`Explore Arcane’s specialist scope at ${p.name} in ${p.location}: ${p.scope} View project facts and related expertise.`,name:p.name,main:detailMain(p,false),image:"/project-"+p.id+".png",record:p});
for(const s of services)pages.push({url:serviceUrl(s),type:"WebPage",section:"expertise",title:s.content.title,description:s.content.description,name:s.name,main:detailMain(s,true),image:"/"+s.image,record:s});
const files={};
for(const page of pages){
 const url=base+page.url;
 const crumbs=[{name:"Home",url:base+"/"}];if(page.record)crumbs.push({name:page.section==="expertise"?"Expertise":"Projects",url:base+"/#"+page.section});if(page.url!=="/")crumbs.push({name:page.name,url});
 const visibleCrumbs=page.url==="/"?"":`<nav class="page-breadcrumb" aria-label="Breadcrumb">${crumbs.map((c,i)=>i===crumbs.length-1?`<span aria-current="page">${esc(c.name)}</span>`:`<a href="${c.url.replace(base,"")}">${esc(c.name)}</a><span aria-hidden="true">/</span>`).join("")}</nav>`;
 if(visibleCrumbs)page.main=page.main.replace('</div><div id="project-details"','</div>'+visibleCrumbs+'<div id="project-details"').replace('</div><section id="company-details"','</div>'+visibleCrumbs+'<section id="company-details"').replace('</div><section id="approach-details"','</div>'+visibleCrumbs+'<section id="approach-details"');
 const web={"@type":page.type,"@id":url+"#webpage",url,name:page.title,description:page.description,isPartOf:{"@id":site["@id"]},publisher:{"@id":org["@id"]},inLanguage:"en"};
 const graph=[org,site,web];
 if(page.url!=="/"){graph.push({"@type":"BreadcrumbList","@id":url+"#breadcrumbs",itemListElement:crumbs.map((c,i)=>({"@type":"ListItem",position:i+1,name:c.name,item:c.url}))});web.breadcrumb={"@id":url+"#breadcrumbs"};}
 if(page.section==="company")web.about={"@id":org["@id"]};
 if(page.section==="expertise"){const s=page.record,entity={"@type":"Service","@id":url+"#service",name:s.name,serviceType:s.name,description:s.scope,url,provider:{"@id":org["@id"]},areaServed:{"@type":"Country",name:"United Arab Emirates"},mainEntityOfPage:{"@id":web["@id"]}};graph.push(entity);web.mainEntity={"@id":entity["@id"]};}
 if(page.section==="projects")web.about={"@type":"Thing",name:page.record.name,description:page.record.scope};
 if(page.section==="home")graph.push({"@type":"ItemList",name:"Arcane specialist expertise",itemListElement:services.map((s,i)=>({"@type":"ListItem",position:i+1,url:base+serviceUrl(s),name:s.name}))});
 let html=shell.replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main">${page.main}</main>`).replace("<body>",`<body data-page-section="${page.section}"${["company","approach"].includes(page.section)?' class="editorial-view"':page.record?' class="project-view"':""}>`);
 html=html.replace(/<title>.*?<\/title>/,`<title>${esc(page.title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(page.description)}">`).replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${url}">`);
 const metadata=`<meta property="og:type" content="website"><meta property="og:site_name" content="Arcane Interior Decorations"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${base+page.image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(page.title)}"><meta name="twitter:description" content="${esc(page.description)}"><meta name="twitter:image" content="${base+page.image}"><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@graph":graph}).replace(/</g,"\\u003c")}</script>`;
 html=html.replace("</head>",metadata+"</head>");
 files[(page.url==="/"?"":page.url.slice(1))+"index.html"]=html;
}
files["arcane-knowledge.js"]="/* Shared website facts and page content. Generated by scripts/build-pages.cjs. */\n(function(){\nconst knowledge="+JSON.stringify(knowledge,null,2)+";\nif(typeof module!=='undefined'&&module.exports)module.exports=knowledge;else window.ArcaneKnowledge=knowledge;\n})();\n";
files["sitemap.xml"]='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+pages.map(p=>"  <url><loc>"+base+p.url+"</loc></url>").join("\n")+"\n</urlset>\n";
files["robots.txt"]="User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /templates/\nDisallow: /content/\nDisallow: /scripts/\nSitemap: "+base+"/sitemap.xml\n";
files["content/page-manifest.json"]=JSON.stringify(pages.map(({url,title,description,section})=>({url,title,description,section})),null,2)+"\n";
return files;
};
const knowledge=require('../arcane-knowledge.js');const copy=JSON.parse(fs.readFileSync(path.join(root,'content/site-copy.json'),'utf8'));const template=fs.readFileSync(path.join(root,'templates/site.html'),'utf8');
const files=generatePages(knowledge,copy,template);for(const [name,content]of Object.entries(files)){const destination=path.join(root,name);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,content);}
console.log('Built 23 static pages, metadata, schema, sitemap and shared assistant knowledge.');
